List<String> financialQuotes = [
  "The stock market is filled with individuals who know the price of everything, but the value of nothing. - Philip Fisher",
  "It's not how much money you make, but how much money you keep, how hard it works for you, and how many generations you keep it for. - Robert Kiyosaki",
  "The individual investor should act consistently as an investor and not as a speculator. - Ben Graham",
  "The stock market is a device for transferring money from the impatient to the patient. - Warren Buffett",
  "Risk comes from not knowing what you're doing. - Warren Buffett",
  "In investing, what is comfortable is rarely profitable. - Robert Arnott",
  "The four most dangerous words in investing are: 'This time it's different.' - Sir John Templeton",
  "The investor's chief problem - and even his worst enemy - is likely to be himself. - Benjamin Graham",
  "The biggest risk is not taking any risk. In a world that is changing quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
  "You get recessions, you have stock market declines. If you don't understand that's going to happen, then you're not ready, you won't do well in the markets. - Peter Lynch",
  "Know what you own, and know why you own it. - Peter Lynch",
  "The best investment you can make is in yourself. - Warren Buffett",
  "Rule No.1: Never lose money. Rule No.2: Never forget Rule No.1. - Warren Buffett",
  "The secret to investing is to figure out the value of something – and then pay a lot less. - Joel Greenblatt",
  "Buy when everyone else is selling and hold until everyone else is buying. That’s not just a catchy slogan. It’s the very essence of successful investing. - J. Paul Getty",
  "An investment in knowledge pays the best interest. - Benjamin Franklin",
  "The stock market is designed to transfer money from the active to the patient. - Warren Buffett",
  "In the short run, the market is a voting machine, but in the long run, it is a weighing machine. - Benjamin Graham",
  "It's not whether you're right or wrong, but how much money you make when you're right and how much you lose when you're wrong. - George Soros",
  "The best time to invest was 20 years ago. The second-best time is now. - Chinese Proverb",
  "Opportunities come infrequently. When it rains gold, put out the bucket, not the thimble. - Warren Buffett",
  "The more you learn, the more you earn. - Warren Buffett",
  "The investor of today does not profit from yesterday’s growth. - Warren Buffett",
  "The most important quality for an investor is temperament, not intellect. - Warren Buffett",
  "Investing should be more like watching paint dry or watching grass grow. If you want excitement, take \$800 and go to Las Vegas. - Paul Samuelson",
  "The market can stay irrational longer than you can stay solvent. - John Maynard Keynes",
  "The only true test of whether a stock is \"cheap\" or \"high\" is not its current price in relation to some former price, no matter how accustomed we may have become to that former price, but whether the company's fundamentals are significantly more or less favorable than the current financial-community appraisal of that stock. - Benjamin Graham",
  "The time of maximum pessimism is the best time to buy, and the time of maximum optimism is the best time to sell. - John Templeton",
  "The best investment you can make is in yourself. - Warren Buffett",
  "You don't need to be a rocket scientist. Investing is not a game where the guy with the 160 IQ beats the guy with 130 IQ. - Warren Buffett",
  "If you aren't thinking about owning a stock for 10 years, don't even think about owning it for 10 minutes. - Warren Buffett",
  "Investing should be more like watching paint dry or watching grass grow. If you want excitement, take \$800 and go to Las Vegas. - Paul Samuelson",
  "Investing puts money to work. The only reason to save money is to invest it. - Grant Cardone",
  "The key to making money in stocks is not to get scared out of them. - Peter Lynch",
  "When you buy something, you should not do so because you think it's going to go up tomorrow. You should buy something because you think that's what you want to own for the next ten years. - Warren Buffett",
  "The stock market is filled with individuals who know the price of everything, but the value of nothing. - Philip Fisher",
  "It's far better to buy a wonderful company at a fair price than a fair company at a wonderful price. - Warren Buffett",
  "Buy when everyone else is selling and hold until everyone else is buying. That’s not just a catchy slogan. It’s the very essence of successful investing. - J. Paul Getty",
  "The stock market is designed to transfer money from the active to the patient. - Warren Buffett",
  "In the short run, the market is a voting machine, but in the long run, it is a weighing machine. - Benjamin Graham",
  "The best time to invest was 20 years ago. The second-best time is now. - Chinese Proverb",
  "Opportunities come infrequently. When it rains gold, put out the bucket, not the thimble. - Warren Buffett",
  "The more you learn, the more you earn. - Warren Buffett",
  "The investor of today does not profit from yesterday’s growth. - Warren Buffett",
  "The most important quality for an investor is temperament, not intellect. - Warren Buffett",
  "Investing should be more like watching paint dry or watching grass grow. If you want excitement, take \$800 and go to Las Vegas. - Paul Samuelson",
  "The market can stay irrational longer than you can stay solvent. - John Maynard Keynes",
  "The only true test of whether a stock is \"cheap\" or \"high\" is not its current price in relation to some former price, no matter how accustomed we may have become to that former price, but whether the company's fundamentals are significantly more or less favorable than the current financial-community appraisal of that stock. - Benjamin Graham",
  "The time of maximum pessimism is the best time to buy, and the time of maximum optimism is the best time to sell. - John Templeton",
  "The best investment you can make is in yourself. - Warren Buffett",
  "You don't need to be a rocket scientist. Investing is not a game where the guy with the 160 IQ beats the guy with 130 IQ. - Warren Buffett",
  "If you aren't thinking about owning a stock for 10 years, don't even think about owning it for 10 minutes. - Warren Buffett",
  "Investing should be more like watching paint dry or watching grass grow. If you want excitement, take \$800 and go to Las Vegas. - Paul",
];
